version: '3.9'
services:
  # MongoDB Servid
  mongo:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./Database/db:/data/db

  # Node
  node:
    build: .
    ports:
      - 3000:3000
    container_name: node_server
    image: node:18.12.0-alpine
    depends_on:
      - mongo
    external_links:
      - mongo
    volumes:
      - ./:/app
